name: Test Aplication
on: [push, pull_request]
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Test project with Maven
        run: mvn -B test --file pom.xml

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18

      - name: Build project with Maven
        run: mvn -B package --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: [ test_and_build ]
    steps:
      - name: Download repository
      - uses: actions/checkout@v2

      - name: Set up JDK 18 and publish
      - uses: actions/setup-java@v1
        with:
          java-version: 18
      - run: mvn -B package --file pom.xml -DskipTests
      - run: mkdir staging && cp target/*jar-with-dependencies.jar staging

      - uses: actions/upload-artifact@v1
        with:
          name: Create package
          path: staging